### ISSUE TITLE
Python for Ansible

### ISSUE THREAD

**Issue by jasperf** [aligajani/ansible-playbooks-laravel-5#2]
Perhaps something like
```
- name: Install prerequisites
  hosts: web
  remote_user: root
  gather_facts: false
  tasks:
    - name: Install Python 2.x
      raw: which python || apt-get update && apt-get install -qq -y python-simplejson
      register: python_check
      changed_when: not python_check.stdout | search('/usr/bin/python')

```
could be added to install Python using a role or addition to the playbook. This would remove the need to run the Python setup on the remote box manually.
